name: Test S3 Cache

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test_binary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # ensures we fetch tag history for the repository
          fetch-depth: 0

      - name: install go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          # use version from go.mod file
          go-version-file: 'go.mod'
          cache: true
          check-latest: true

      - name: build s3-cache plugin binary
        run: |
          make build

      # install node to create a folder to cache
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: latest

      - name: install eslint
        run: |
          npm init -y
          npm install eslint

      - name: start S3Mock
        run: |
          docker run -d -p 9000:9090 --name s3mock \
            -e COM_ADOBE_TESTING_S3MOCK_STORE_INITIAL_BUCKETS=test-bucket \
            -e COM_ADOBE_TESTING_S3MOCK_STORE_REGION=us-east-1 \
            adobe/s3mock:5.2.3@sha256:ab01a6946750f451ca215a47e91030695b260e4003b8a5a6201d25029b8fca92

      - name: wait for S3Mock
        timeout-minutes: 1
        run: |
          until curl -fsS http://localhost:9000/favicon.ico; do
            sleep 5
          done

      - name: test rebuild action
        env:
          S3_CACHE_ACCESS_KEY: minioadmin
          S3_CACHE_SECRET_KEY: minioadmin
          S3_CACHE_BUCKET: test-bucket
          S3_CACHE_SERVER: http://localhost:9000
          VELA_REPO_ORG: test
          VELA_REPO_NAME: test
        run: |
          ./release/vela-s3-cache --config.action=rebuild --rebuild.mount=node_modules
          mv node_modules node_modules_original

      - name: test restore action
        env:
          S3_CACHE_ACCESS_KEY: minioadmin
          S3_CACHE_SECRET_KEY: minioadmin
          S3_CACHE_BUCKET: test-bucket
          S3_CACHE_SERVER: http://localhost:9000
          VELA_REPO_ORG: test
          VELA_REPO_NAME: test
        run: |
          ./release/vela-s3-cache --config.action=restore

      - name: check
        run: |
          if ! diff -rq --no-dereference node_modules node_modules_original; then
            echo "differences found between node_modules and node_modules_original"
            exit 1
          else
            echo "no differences found - cache restored successfully"
          fi

  test_docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # ensures we fetch tag history for the repository
          fetch-depth: 0

      - name: install go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          # use version from go.mod file
          go-version-file: 'go.mod'
          cache: true
          check-latest: true

      - name: build s3-cache plugin binary
        run: |
          make build

      - name: build docker image
        run: |
          make docker-build

      # install node to create a folder to cache
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: latest

      - name: install eslint
        run: |
          npm init -y
          npm install eslint

      - name: start S3Mock
        run: |
          docker run -d -p 9000:9090 --name s3mock \
            -e COM_ADOBE_TESTING_S3MOCK_STORE_INITIAL_BUCKETS=test-bucket \
            -e COM_ADOBE_TESTING_S3MOCK_STORE_REGION=us-east-1 \
            adobe/s3mock:5.2.3@sha256:ab01a6946750f451ca215a47e91030695b260e4003b8a5a6201d25029b8fca92

      - name: wait for S3Mock
        timeout-minutes: 1
        run: |
          until curl -fsS http://localhost:9000/favicon.ico; do
            sleep 5
          done

      - name: test rebuild action
        run: |
          docker run -v $(pwd):/src -w /src \
          --network=host \
          -e S3_CACHE_SERVER="http://localhost:9000" \
          -e S3_CACHE_ACCESS_KEY=minioadmin \
          -e S3_CACHE_SECRET_KEY=minioadmin \
          -e S3_CACHE_BUCKET=test-bucket \
          -e VELA_REPO_ORG=org \
          -e VELA_REPO_NAME=repo \
          -e S3_CACHE_ACTION=rebuild \
          -e S3_CACHE_MOUNT=node_modules \
          vela-s3-cache:local 
          mv node_modules node_modules_original

      - name: test restore action
        run: |
          docker run -v $(pwd):/src -w /src \
          --network=host \
          -e S3_CACHE_SERVER="http://localhost:9000" \
          -e S3_CACHE_ACCESS_KEY=minioadmin \
          -e S3_CACHE_SECRET_KEY=minioadmin \
          -e S3_CACHE_BUCKET=test-bucket \
          -e VELA_REPO_ORG=org \
          -e VELA_REPO_NAME=repo \
          -e S3_CACHE_ACTION=restore \
          vela-s3-cache:local

      - name: check
        run: |
          if ! diff -rq --no-dereference node_modules node_modules_original; then
            echo "differences found between node_modules and node_modules_original"
            exit 1
          else
            echo "no differences found - cache restored successfully"
          fi
