# name of the action
name: prerelease

# trigger on push events with `v*` in tag
on:
  push:
    tags:
      - "v*"

# pipeline to execute
jobs:
  prerelease:
    runs-on: ubuntu-latest

    steps:
      - name: clone
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          # ensures we fetch tag history for the repository
          fetch-depth: 0

      - name: install go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          # use version from go.mod file
          go-version-file: "go.mod"
          cache: true
          check-latest: true

      - name: setup
        run: |
          # setup git tag in Actions environment
          echo "GITHUB_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: build
        env:
          GOOS: linux
          CGO_ENABLED: "0"
        run: |
          make build-static-ci

      - name: publish
        uses: elgohr/Publish-Docker-Github-Action@4feac4d53e4e55dcc5d3e2ad0ed2e0a76028ff7a # v5
        with:
          name: target/vela-s3-cache
          cache: true
          tag_names: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
