# name of the action
name: reviewdog

# trigger on pull_request events
on:
  pull_request:

permissions:
  contents: read

# pipeline to execute
jobs:
  diff-review:
    runs-on: ubuntu-latest

    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: write # for reviewdog/action-golangci-lint to report issues using PR comments

    steps:
      - name: clone
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: install go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          # use version from go.mod file
          go-version-file: 'go.mod'
          cache: true
          check-latest: true

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@f9bba13753278f6a73b27a56a3ffb1bfda90ed71 # v2.8.0
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: '--config=.golangci.yml --timeout=5m'
          fail_level: error
          filter_mode: diff_context
          reporter: github-pr-review

  full-review:
    runs-on: ubuntu-latest

    permissions:
      checks: write # for reviewdog/action-golangci-lint to report issues using checks
      contents: read # for actions/checkout to fetch code

    steps:
      - name: clone
<<<<<<< HEAD
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
||||||| 474f153
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
=======
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
>>>>>>> b4637a1c80fbe1df8351e4929b6d0d8ae6344e2c

      - name: install go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          # use version from go.mod file
          go-version-file: 'go.mod'
          cache: true
          check-latest: true

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@f9bba13753278f6a73b27a56a3ffb1bfda90ed71 # v2.8.0
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: '--config=.golangci.yml --timeout=5m'
          fail_level: error
          filter_mode: nofilter
